### ISSUE TITLE
[DEP0060] DeprecationWarning

### ISSUE THREAD

**Issue by senarclens** [KevinGimbel/eleventy-plugin-mermaid#8]
After recently updating my system, when running a build with

```
npx --version
10.8.3
```

There now is a DepeciationWarning. To trace the warning, I started the build (server) via

```
NODE_OPTIONS='--trace-deprecation' npm run serve
```

and the output is

```
(node:349871) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
    at Object.<anonymous> ($PROJECTPATH/node_modules/htmlencode/index.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> ($PROJECTPATH/node_modules/@kevingimbel/eleventy-plugin-mermaid/.eleventy.js:1:20)
```

Would be great if you could have a look.
Thanks!

---
 If needed, my project is available at https://gitlab.com/senarclens/htl-bulme

**Comment by KevinGimbel** [comment]
Will have a look, thanks for bringing it to my attentions!

**Comment by KevinGimbel** [comment]
Ah well, the dependency hasn't been updated in 12 years! :D https://github.com/danmactough/node-htmlencode 

Will need to find a replacement or fork it.
